
name: 'hr_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  hr_project:
    staging:
      schema: staging
      +materialized: table
    intermediate:
      schema: intermediate
      +materialized: table
    mart:
      schema: mart
      +materialized: table

