version: 2

sources:
  - name: dataset
    schema: HR_datasets
    description: "All HR datas"
    tables:
      - name: general
        identifier: general_data
        description: "HR general data"
        columns:
          - name: Age
            description: "Age of the employee"
          - name: Attrition
            description: "Whether the employee has left the company"
          - name: BusinessTravel
            description: "Frequency of business travel"
          - name: Department
            description: "Department the employee works in"
          - name: DistanceFromHome
            description: "Distance from home to work"
          - name: Education
            description: "Education level"
          - name: EducationField
            description: "Field of study"
          - name: EmployeeCount
            description: "Employee count (usually 1 for individual records)"
          - name: EmployeeID
            description: "Unique identifier for each employee"
          - name: Gender
            description: "Gender of the employee"
          - name: JobLevel
            description: "Level of the job"
          - name: JobRole
            description: "Role of the job"
          - name: MaritalStatus
            description: "Marital status of the employee"
          - name: MonthlyIncome
            description: "Monthly income of the employee"
          - name: NumCompaniesWorked
            description: "Number of companies the employee has worked for"
          - name: Over18
            description: "Indicates if the employee is over 18"
          - name: PercentSalaryHike
            description: "Percentage of the last salary hike"
          - name: StandardHours
            description: "Standard hours of work (may be a fixed value)"
          - name: StockOptionLevel
            description: "Level of the stock options"
          - name: TotalWorkingYears
            description: "Total years of work experience"
          - name: TrainingTimesLastYear
            description: "Number of times trained last year"
          - name: YearsAtCompany
            description: "Number of years spent at the company"
          - name: YearsSinceLastPromotion
            description: "Years since the last promotion"
          - name: YearsWithCurrManager
            description: "Years with the current manager"
      - name: employee_survey_data
        identifier: employee_survey_data
        description: "Survey data related to employees"
        columns:
          - name: EmployeeID
            description: "Unique identifier for each employee"
          - name: EnvironmentSatisfaction
            description: "Satisfaction with the work environment"
          - name: JobSatisfaction
            description: "Satisfaction with the job"
          - name: WorkLifeBalance
            description: "Perception of work-life balance"
      - name: manager_survey_data
        identifier: manager_survey_data
        description: "Survey data related to managers' assessments of employees"
        columns:
          - name: EmployeeID
            description: "Unique identifier for each employee, matching their record in other tables"
          - name: JobInvolvement
            description: "Degree of the employee's involvement in their job"
          - name: PerformanceRating
            description: "Rating of the employee's overall performance"
      - name: df_time_calculated
        description: "Time calculation data for employees"
        columns:
          - name: EmployeeID
            description: "Unique identifier for each employee"

          - name: _2015_01_01

          - name: _2015_01_02

          - name: _2015_01_05

          - name: _2015_01_06

          - name: _2015_01_07

          - name: _2015_01_08

          - name: _2015_01_09

          - name: _2015_01_12

          - name: _2015_01_13

          - name: _2015_01_14

          - name: _2015_01_15

          - name: _2015_01_16

          - name: _2015_01_19

          - name: _2015_01_20

          - name: _2015_01_21

          - name: _2015_01_22

          - name: _2015_01_23

          - name: _2015_01_26

          - name: _2015_01_27

          - name: _2015_01_28

          - name: _2015_01_29

          - name: _2015_01_30

          - name: _2015_02_02

          - name: _2015_02_03

          - name: _2015_02_04

          - name: _2015_02_05

          - name: _2015_02_06

          - name: _2015_02_09

          - name: _2015_02_10

          - name: _2015_02_11

          - name: _2015_02_12

          - name: _2015_02_13

          - name: _2015_02_16

          - name: _2015_02_17

          - name: _2015_02_18

          - name: _2015_02_19

          - name: _2015_02_20

          - name: _2015_02_23

          - name: _2015_02_24

          - name: _2015_02_25

          - name: _2015_02_26

          - name: _2015_02_27

          - name: _2015_03_02

          - name: _2015_03_03

          - name: _2015_03_04

          - name: _2015_03_05

          - name: _2015_03_06

          - name: _2015_03_09

          - name: _2015_03_10

          - name: _2015_03_11

          - name: _2015_03_12

          - name: _2015_03_13

          - name: _2015_03_16

          - name: _2015_03_17

          - name: _2015_03_18

          - name: _2015_03_19

          - name: _2015_03_20

          - name: _2015_03_23

          - name: _2015_03_24

          - name: _2015_03_25

          - name: _2015_03_26

          - name: _2015_03_27

          - name: _2015_03_30

          - name: _2015_03_31

          - name: _2015_04_01

          - name: _2015_04_02

          - name: _2015_04_03

          - name: _2015_04_06

          - name: _2015_04_07

          - name: _2015_04_08

          - name: _2015_04_09

          - name: _2015_04_10

          - name: _2015_04_13

          - name: _2015_04_14

          - name: _2015_04_15

          - name: _2015_04_16

          - name: _2015_04_17

          - name: _2015_04_20

          - name: _2015_04_21

          - name: _2015_04_22

          - name: _2015_04_23

          - name: _2015_04_24

          - name: _2015_04_27

          - name: _2015_04_28

          - name: _2015_04_29

          - name: _2015_04_30

          - name: _2015_05_01

          - name: _2015_05_04

          - name: _2015_05_05

          - name: _2015_05_06

          - name: _2015_05_07

          - name: _2015_05_08

          - name: _2015_05_11

          - name: _2015_05_12

          - name: _2015_05_13

          - name: _2015_05_14

          - name: _2015_05_15

          - name: _2015_05_18

          - name: _2015_05_19

          - name: _2015_05_20

          - name: _2015_05_21

          - name: _2015_05_22

          - name: _2015_05_25

          - name: _2015_05_26

          - name: _2015_05_27

          - name: _2015_05_28

          - name: _2015_05_29

          - name: _2015_06_01

          - name: _2015_06_02

          - name: _2015_06_03

          - name: _2015_06_04

          - name: _2015_06_05

          - name: _2015_06_08

          - name: _2015_06_09

          - name: _2015_06_10

          - name: _2015_06_11

          - name: _2015_06_12

          - name: _2015_06_15

          - name: _2015_06_16

          - name: _2015_06_17

          - name: _2015_06_18

          - name: _2015_06_19

          - name: _2015_06_22

          - name: _2015_06_23

          - name: _2015_06_24

          - name: _2015_06_25

          - name: _2015_06_26

          - name: _2015_06_29

          - name: _2015_06_30

          - name: _2015_07_01

          - name: _2015_07_02

          - name: _2015_07_03

          - name: _2015_07_06

          - name: _2015_07_07

          - name: _2015_07_08

          - name: _2015_07_09

          - name: _2015_07_10

          - name: _2015_07_13

          - name: _2015_07_14

          - name: _2015_07_15

          - name: _2015_07_16

          - name: _2015_07_17

          - name: _2015_07_20

          - name: _2015_07_21

          - name: _2015_07_22

          - name: _2015_07_23

          - name: _2015_07_24

          - name: _2015_07_27

          - name: _2015_07_28

          - name: _2015_07_29

          - name: _2015_07_30

          - name: _2015_07_31

          - name: _2015_08_03

          - name: _2015_08_04

          - name: _2015_08_05

          - name: _2015_08_06

          - name: _2015_08_07

          - name: _2015_08_10

          - name: _2015_08_11

          - name: _2015_08_12

          - name: _2015_08_13

          - name: _2015_08_14

          - name: _2015_08_17

          - name: _2015_08_18

          - name: _2015_08_19

          - name: _2015_08_20

          - name: _2015_08_21

          - name: _2015_08_24

          - name: _2015_08_25

          - name: _2015_08_26

          - name: _2015_08_27

          - name: _2015_08_28

          - name: _2015_08_31

          - name: _2015_09_01

          - name: _2015_09_02

          - name: _2015_09_03

          - name: _2015_09_04

          - name: _2015_09_07

          - name: _2015_09_08

          - name: _2015_09_09

          - name: _2015_09_10

          - name: _2015_09_11

          - name: _2015_09_14

          - name: _2015_09_15

          - name: _2015_09_16

          - name: _2015_09_17

          - name: _2015_09_18

          - name: _2015_09_21

          - name: _2015_09_22

          - name: _2015_09_23

          - name: _2015_09_24

          - name: _2015_09_25

          - name: _2015_09_28

          - name: _2015_09_29

          - name: _2015_09_30

          - name: _2015_10_01

          - name: _2015_10_02

          - name: _2015_10_05

          - name: _2015_10_06

          - name: _2015_10_07

          - name: _2015_10_08

          - name: _2015_10_09

          - name: _2015_10_12

          - name: _2015_10_13

          - name: _2015_10_14

          - name: _2015_10_15

          - name: _2015_10_16

          - name: _2015_10_19

          - name: _2015_10_20

          - name: _2015_10_21

          - name: _2015_10_22

          - name: _2015_10_23

          - name: _2015_10_26

          - name: _2015_10_27

          - name: _2015_10_28

          - name: _2015_10_29

          - name: _2015_10_30

          - name: _2015_11_02

          - name: _2015_11_03

          - name: _2015_11_04

          - name: _2015_11_05

          - name: _2015_11_06

          - name: _2015_11_09

          - name: _2015_11_10

          - name: _2015_11_11

          - name: _2015_11_12

          - name: _2015_11_13

          - name: _2015_11_16

          - name: _2015_11_17

          - name: _2015_11_18

          - name: _2015_11_19

          - name: _2015_11_20

          - name: _2015_11_23

          - name: _2015_11_24

          - name: _2015_11_25

          - name: _2015_11_26

          - name: _2015_11_27

          - name: _2015_11_30

          - name: _2015_12_01

          - name: _2015_12_02

          - name: _2015_12_03

          - name: _2015_12_04

          - name: _2015_12_07

          - name: _2015_12_08

          - name: _2015_12_09

          - name: _2015_12_10

          - name: _2015_12_11

          - name: _2015_12_14

          - name: _2015_12_15

          - name: _2015_12_16

          - name: _2015_12_17

          - name: _2015_12_18

          - name: _2015_12_21

          - name: _2015_12_22

          - name: _2015_12_23

          - name: _2015_12_24

          - name: _2015_12_25

          - name: _2015_12_28

          - name: _2015_12_29

          - name: _2015_12_30

          - name: _2015_12_31
